def errorPrint(error):
    print('Error occured: ' + str(error))
    exit()